apiVersion: v1
kind: Secret
metadata:
  name: portfolio-credentials
  namespace: default
type: Opaque
stringData:
  # Firebase Configuration
  NEXT_PUBLIC_FIREBASE_API_KEY: ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ""
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ""
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ""
  NEXT_PUBLIC_FIREBASE_APP_ID: ""
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ""

  # Cloudflare R2 Storage
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""
  R2_ACCOUNT_ID: ""
  AWS_S3_CUSTOM_DOMAIN: ""
